### ISSUE TITLE
function name error

### ISSUE THREAD

**Issue by Jihyun-K** [jijih19/SoftwareEngineering#1]
지현아....
너가 Calcultor클래스에서 kg->pound짠 함수 이름이 거꾸로된거같아서.....
내가 고칠께....

![image](https://user-images.githubusercontent.com/33978996/33474762-419a540a-d6bf-11e7-8ff9-175c62858b66.png)

**Comment by jijih19** [comment]
메일이 안왔어 ㅠ
아 그 이름 잘못 적은 것같아 ㅠㅠ
그리고 코딩할때 우리가 userstroy에서  "출력하시오" 같은 문장들은 
마지막에 다 같이 적어버리려고 안적었어!!!

**Comment by jijih19** [comment]
웅웅 ㅠ
고마워 근데 니꺼 메일안왔어 ㅠ
왜 니메일 안왔지?
다시한번 이슈 올려줄래 ?
