### ISSUE TITLE
@Jihyun-K MemoManager

### ISSUE THREAD

**Issue by Jooyeonleee** [jijih19/SoftwareEngineering#9]
1.  내용 입력후 저장되었습니다 라는 문구 프린트 필요해
2.  MemoManager에서 입력된 메모 순서 매길 때 Arraylist 써서 0번째부터 되잖아. 이거 나 코드 짤 때 그냥 +1해서 출력될 때 첫번째 메모부터 있게 했거든. 일단 그렇게 했는데 너 코딩해보고 혹시 0번째부터 하는게 낫다 싶음 말해줘

**Comment by Jihyun-K** [comment]
상관없을꺼같오~ 그렇게하자
